// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9tYa9tdtoEKUoJl6Gu1tmpMMdbCVQopI',
    appId: '1:406719502396:web:0543102c00b3c3db0a0b39',
    messagingSenderId: '406719502396',
    projectId: 'ohs-hausaufgaben',
    authDomain: 'ohs-hausaufgaben.firebaseapp.com',
    storageBucket: 'ohs-hausaufgaben.appspot.com',
    measurementId: 'G-VVLZMNDE6R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7srtBOTLyIUlT0WA7DE-IM1naJ1nx1rg',
    appId: '1:406719502396:android:f708d7a3e31e502d0a0b39',
    messagingSenderId: '406719502396',
    projectId: 'ohs-hausaufgaben',
    storageBucket: 'ohs-hausaufgaben.appspot.com',
  );
}
